name: Build & push container images
run-name: Build container images for ${{ gitea.repository }} by @${{ gitea.actor }}
on: [push, pull_request, tag]

jobs:
  build-push:
    runs-on: amd64
    env:
      IMAGE_NAME: git.ingenius.dev/${{ gitea.repository }}
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: https://github.com/docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ gitea.ref == format('refs/heads/{0}', 'main') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        if: ${{ gitea.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: git.ingenius.dev
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ gitea.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
